"""add created_by for community

Revision ID: 1838138b67fb
Revises: None
Create Date: 2013-12-17 03:26:04.392578

"""

# revision identifiers, used by Alembic.
revision = '1838138b67fb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.drop_column('post', u'modified')
    op.drop_column('post', u'created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column(u'created', sa.DATETIME(), nullable=True))
    op.add_column('post', sa.Column(u'modified', sa.DATETIME(), nullable=True))
    op.drop_column('post', 'modified_on')
    op.drop_column('post', 'created_on')
    op.drop_column('community', 'created_on')
    ### end Alembic commands ###
