"""update events schema

Revision ID: 1f14fdfaf545
Revises: 1838138b67fb
Create Date: 2013-12-17 03:59:14.627776

"""

# revision identifiers, used by Alembic.
revision = '1f14fdfaf545'
down_revision = '1838138b67fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('event', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('end_on', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('modified_on', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('start_on', sa.DateTime(), nullable=False))
    op.drop_column('event', u'date')

    op.alter_column('post', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('post', 'modified_on',
               existing_type=sa.DATETIME(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'modified_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('post', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('event', sa.Column(u'date', sa.DATETIME(), nullable=False))
    op.drop_column('event', 'start_on')
    op.drop_column('event', 'modified_on')
    op.drop_column('event', 'modified_by')
    op.drop_column('event', 'end_on')
    op.drop_column('event', 'created_on')
    op.drop_column('event', 'created_by')
    op.alter_column('community', 'created_on',
               existing_type=sa.DATETIME(),
               nullable=True)
    ### end Alembic commands ###
