"""first migration

Revision ID: 2dcdd1ea33a0
Revises: None
Create Date: 2013-12-12 18:21:16.775901

"""

# revision identifiers, used by Alembic.
revision = '2dcdd1ea33a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('parent_id', 'post')
    op.drop_index('wall_id', 'post')
    op.drop_index('user_id', 'post')
    op.drop_index('community_id', 'post')
    op.drop_index('user_id', 'user_community')
    op.drop_index('community_id', 'user_community')
    op.drop_index('community_id', 'wall')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('community_id', 'wall', [u'community_id'], unique=False)
    op.create_index('community_id', 'user_community', [u'community_id'], unique=False)
    op.create_index('user_id', 'user_community', [u'user_id', u'community_id'], unique=True)
    op.create_index('community_id', 'post', [u'community_id'], unique=False)
    op.create_index('user_id', 'post', [u'user_id'], unique=False)
    op.create_index('wall_id', 'post', [u'wall_id'], unique=False)
    op.create_index('parent_id', 'post', [u'parent_id'], unique=False)
    ### end Alembic commands ###
