"""Added some tables

Revision ID: 32e6227c9e67
Revises: 545c0ca6d95b
Create Date: 2013-12-28 20:27:23.041535

"""

# revision identifiers, used by Alembic.
revision = '32e6227c9e67'
down_revision = '545c0ca6d95b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_feed',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column(u'task', sa.Column('description', sa.String(length=1000), nullable=False))
    op.drop_column(u'task', u'Description')
    op.drop_constraint(u'ix_user_email', 'user')
    op.drop_constraint(u'ix_user_user_name', 'user')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'ix_user_user_name', 'user', [u'user_name'])
    op.create_unique_constraint(u'ix_user_email', 'user', [u'email'])
    
    op.add_column(u'task', sa.Column(u'Description', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_column(u'task', 'description')
    op.drop_table('notification')
    op.drop_table('activity_feed')
    ### end Alembic commands ###
