"""Add fb_id to user

Revision ID: 40700ad5d0fd
Revises: None
Create Date: 2013-12-30 15:53:02.183954

"""

# revision identifiers, used by Alembic.
revision = '40700ad5d0fd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_id', sa.BigInteger(unsigned=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fb_id')
    ### end Alembic commands ###
